const workPageOrder = {
    featured: [
      "Transforming how Indian SMBs Hire",
      "220% Organic YouTube Subscriber Growth in India",
      "Global Leaders: a Hiring Campaign",
      "Action-packed launch film for Redmi Buds 6",
      "Never sweat the first game Campaign Films",
      "Campaign: When you can't resist buying more",
      "Launching an AI-powered healthcare brand in record time",
      "Branding and Launch Campaign for a Dessert Cafe",
      "Powering education in war-torn Ukraine, with Street Child",
      "Sales Digitisation Campaign - Interactive Explainer",
      "Exicom Brand Refresh: Choose Smart. Charge Smart.",
      "Gordon Ritter on the Future of Software",
      "Augmented Reality that brought the automobile alive",
      "Immersive 3D Walkthrough for Infosys Topaz",
      "Transforming relationships for SME banks in U.S.A",
      "Crafting a Unified Employer Brand Across Continents",
      "Explainer Video for HRM SAAS product",
      "AI-Powered Campaign That Inspires Employees To Imagine Their Best Selves"
    ],

    videos: [
      "Global Leaders: a Hiring Campaign",
      "220% Organic YouTube Subscriber Growth in India",
      "Campaign Explainer Video for HRM SAAS product",
      "Gordon Ritter on the Future of Software",
      "Capturing the Story of Sanganeri Craft for Taneira",
      "Celebrating Rural Women in India's Auto Manufacturing",
      "Unveiling Harmony Direct 2.0 - Electric Fleet Charger",
      "Global Case Study Videos for Infosys",
      "HIRING STEM EDUCATORS FOR INDONESIA",
      "Powering education in war-torn Ukraine, with Street Child",
      "Social Media Campaign: Meet the AI-First Employees",
      "Launching a Sports Brand logo with a 3D Billboard",
      "A GenAI Microdrama for Bharat",
      "An ode to the Security Personnel who Guard our Homes",
      "A Campaign film for Xiaomi Pocket Power Bank",
      "Launching the Cobalt Cloud Community",
      "#HeroesAtMyGate: Celebrating India’s Security Guards",
      "Celebrating Wipro’s journey and growth in Australia",
      "Gen AI Ad for Single-Origin Coffee Range",
      "High-energy rap music video on Tata Women’s Cricket Premiere League",
      "Anywhere chat support for Delivery Executives",
      "How Hansel Helps Brands Boost Conversions",
      "Sales Digitisation Campaign - Interactive Explainer",
      "IT Consulting firm delivers Business Agility Solution",
      "Corporate Film for Aerospace Manufacturing giant in India",
      "Documentaries: Traditional Indian Handlooms and Weavers",
      "Hiring for ’Hotel Superhero’, hospitality SAAS",
      "How a Healthtech Startup Gamified Workplace Wellness",
      "Documentaries: Indian Handcrafted Jewellery and Craftspeople",
      "HEALTHTECH AND INSURTECH CASE STUDY VIDEOS FOR HIMSS",
      "Highlighting the impact of Dozee Beds in India's Healthcare",
      "Immersive 3D Walkthrough for Infosys Topaz",
      "Koo Launches Self-Verification",
      "A hiring video with humor and heart",
      "Launching the Cyanotype clothing range",
      "Transforming relationships for SME banks in U.S.A",
      "Stories of Innovation & Impact at Texas instruments India",
      "Inspiring Campus Recruitment Video",
      "Supporting young women in pursuit of a Future in STEM",
      "The Lakshmi Rebecca Show: YouTube Series on Impact Businesses",
      "Crafting a Unified Employer Brand Across Continents",
      "Launching a brand that makes commerce human",
      "A Vision for Sustainable Social Housing",
      "Building Pathways for Skilled Plumbers",
      "Case Study Video: Tech for Safe Mining"
    ],

    design: [
      "Launching an AI-powered healthcare brand in record time",
      "Exicom Brand Refresh: Choose Smart. Charge Smart.",
      "Branding for an Indulgent Dessert Café",
      "Crafting a Symbol of Success in Hospitality",
      "Branding for a Desi Street Food Restaurant",
      "ABIS Pro Brand Identity: Goodness. Guaranteed.",
      "Augmented Reality that brought the automobile alive",
      "Immersive 3D Walkthrough for Infosys Topaz",
      "Nationwide Activation Celebrating Customer Obsession",
      "Social Media Campaign: Meet the AI-First Employees",
      "Launching a Sports Brand logo with a 3D Billboard",
      "A Design Gallery on Sustainability",
      "Office Branding for Biocon's Global Headquarters"
    ],

    campaign: [
      "Transforming how Indian SMBs Hire",
      "Action-packed campaign film for Redmi Buds 6",
      "Transforming relationships for SME banks in U.S.A",
      "Global Leaders: a Hiring Campaign",
      "Branding and Launch Campaign for a Dessert Cafe",
      "Campaign films: Season's EXTRA Earnings",
      "Launching a brand that makes commerce human",
      "Launch Campaign for Redmi A4 5G",
      "Campaign film for Door Step Gold Loans",
      "Crafting a Unified Employer Brand Across Continents",
      "Trip Different with L74 Ciders",
      "Never sweat the first game Campaign Films",
      "Social Media Campaign: Meet the AI-First Employees",
      "A Trimmer Launch Campaign that’s as Sharp as the Product",
      "Digital Campaign videos for E-learning courses",
      "AI-Powered Campaign That Inspires Employees To Imagine Their Best Selves",
      "Launch Campaign for Redmi Buds 5C",
      "Augmented Reality that brought the automobile alive",
      "Campaign on Inclusive Lingerie",
      "5 Star Quality at Wholesale Prices",
      "A Lead Management Product for Financial Services",
      "A Campaign film for Xiaomi Pocket Power Bank",
      "AI-powered Singalong Campaign that united a Global Workforce",
      "Campaign: When you can't resist buying more",
      "Campaign films: Winter Jackets",
      "Transforming Field Sales for Insurance Wholesalers in USA"
    ],
};
export default workPageOrder;
